import "./tahoma.ttf";
import { Button, StandardButton } from "std-widgets.slint";

component FormPart inherits HorizontalLayout {
    in property <string> note;
    in property <string> label;
    in property <length> input_width;
    width: input_width;

    Text {
        vertical-alignment: center;
        color: black;
        text: parent.label;
        horizontal-alignment: right;
        width: 95px;
    }
    Rectangle {
        width: 9px;
    }
    Rectangle {
        clip: true;
        background: white;
        border-color: input.has-focus ? #0078D7 : black;
        border-width: 1px;
        height: 23px;
        width: parent.input_width; // 174px

        input := TextInput {
            x: 7px;
            y: 3px;
            color: black;
        }
    }

    Rectangle {
        width: 11px;
    }
    Text {
        vertical-alignment: center;
        color: #303030;
        text: parent.note;
        horizontal-alignment: center;
    }
}

component WinFormsButton inherits Rectangle {
    in property <bool> default;
    in property <bool> extra;
    in property <string> label;
    callback clicked();

    width: 84px;
    height: 22px;

    border-color: touch.has-hover || default ? #0078D7 : #ADADAD;
    border-width: default ? 2px : 1px;
    background: touch.has-hover ? #C0DDF4 : #E1E1E1;

    touch := TouchArea {
        clicked => {
            parent.clicked();
        }
    }

    Text {
        x: extra ? 2px : 0px;
        y: extra ? 3px : 0px;
        horizontal-alignment: extra ? left : center;
        width: extra ? 104px : 84px;
        height: extra ? 30px : 22px;

        vertical-alignment: center;
        color: black;
        text: parent.label;
        wrap: word-wrap;
    }
}

component WinFormsWindow inherits Window {
    default-font-family: "Tahoma";
    default-font-size: 14px;
    background: #F0F0F0;
    title: "real osage";
    icon: @image-url("inabakumori.png");
}

export component MainWindow inherits WinFormsWindow {
    callback thanks();

    width: 534px;
    height: 246px;
    HorizontalLayout {
        Image {
            source: @image-url("osage-left.png");
            width: 154px;
            image-fit: preserve;
        }
        VerticalLayout {
            padding-left: 9px;
            padding-top: 14px;
            padding-right: 15px;
            alignment: start;
            VerticalLayout {
                padding-right: 42px;
                Text {
                    color: black;
                    text: "i lost my fuckign umbrella again can u give me ur credit cardd information so i can buy another one pls";
                    wrap: word-wrap;
                    width: 306px;
                }
                VerticalLayout {
                    height: 105px;
                    padding-right: 36px;
                    spacing: 5px;
                    alignment: center;
                    FormPart {
                        label: "card number:";
                        input_width: 174px;
                    }
                    FormPart {
                        label: "expiration date:";
                        input_width: 74px;
                        note: "(MM/YY)";
                    }
                    FormPart {
                        label: "security code:";
                        input_width: 74px;
                    }
                }
            }

            Rectangle {
                height: 35px;
            }
            HorizontalLayout {
                alignment: end;
                spacing: 9px;
                WinFormsButton {
                    label: "thank u so much holy fukcj";
                    extra: true;
                    default: true;
                    z: 1.0;
                    clicked => {
                        root.thanks();
                    }
                }
                WinFormsButton {
                    label: "muu";
                }
                WinFormsButton {
                    label: "(gong)";
                }
            }
        }
    }
}

export component PopUp inherits WinFormsWindow {
    callback ok();

    width: 194px;
    height: 136px;
    HorizontalLayout {
        Image {
            source: @image-url("umbrella.png");
            width: 80px;
            image-fit: preserve;
        }
        VerticalLayout {
            padding-left: 1px;
            padding-bottom: 14px;
            padding-right: 15px;
            alignment: end;
            Text {
                vertical-alignment: center;
                horizontal-alignment: center;
                color: black;
                text: "thakns for umberlla";
                wrap: word-wrap;
            }
            Rectangle {
                height: 35px;
            }
            HorizontalLayout {
                alignment: end;
                spacing: 9px;
                WinFormsButton {
                    label: "OK";
                    default: true;
                    clicked => {
                        root.ok();
                    }
                }
            }
        }
    }
}
